x<-read.csv(file.choose(),header=T)
y<-x$Open
y<-ts(data=y,frequency=253)
ylag<-lag(y,k=-1)
ytable<-cbind(y,ylag)
ytable
daily.return<-y/ylag
daily.return
var.dr<-var(daily.return)
var.dr
samplesd<-sqrt(var.dr)
samplesd
length(daily.return)
sigma<-sqrt(length(daily.return)*samplesd) //
sigma
===============================================================
callprice<-function(x,t,T,r,sigma,K)
callprice<-function(x=1,t-0,T=1,r=1,sigma=1,K=1){
d2<-(log(x/K)+(r-(0.5*sigma^2))*(T-t))/(sigma*sqrt(T-t))
d1<-(d2+sigma*sqrt(T-t))
x*pnorm(d1)-K*exp(-r*(T-t))*pnorm(d2)
}
callprice
===============================================================
x<-5400
K<-5500
r<-0.05
t<-0
T<-1/4
sigma<-0.25
---------------------------------------------------------------
C<-callprice(x=x,t=t,T=T,r=r,sigma=sigma,K=K)
===============================================================
require(sde)
set.seed(123)
sigma<-0.5
mu<-1
S<-sde.sim((X0=100,model="BS",theta=c(mu,sigma),T=100,N=10000)
===============================================================


